export const FLICKR_IMAGE_REQUEST = 'FLICKR_IMAGE_REQUEST';
export const FLICKR_IMAGE_REQUEST_SUCCESS = 'FLICKR_IMAGE_REQUEST_SUCCESS';
export const FLICKR_IMAGE_REQUEST_FAILED = 'FLICKR_IMAGE_REQUEST_FAILED';
